# Generated by Django 4.2.5 on 2023-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(null=True),
        ),
    ]
