# Generated by Django 4.2.5 on 2023-12-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
