# Generated by Django 4.2.5 on 2023-12-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
